sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake'